### ISSUE TITLE
ImportError: cannot import name 'Disaggregator' from 'nilmtk.disaggregate' (unknown location)

### ISSUE THREAD

**Issue by Timelesssssss** [OdysseasKr/neural-disaggregator#21]
Why am I wrong here?

![image](https://user-images.githubusercontent.com/45961357/67007565-4294c300-f11a-11e9-8bf2-dba5ae69eb96.png)

**Comment by Timelesssssss** [comment]
After I added the new disaggregator library, a new problem appeared.
![image](https://user-images.githubusercontent.com/45961357/67014142-e7b59880-f126-11e9-93f3-87f39d7d2c20.png)

**Comment by OdysseasKr** [comment]
Hi @Timelesssssss. This code does not run with the latest version of NILMTK yet. I would say please use this disaggregator [class](https://github.com/OdysseasKr/nilmtk/blob/master/nilmtk/disaggregate/disaggregator.py) if you are willing to tinker with NILTMK. 

Otherwise please consider using this instead
https://github.com/nilmtk/nilmtk-contrib/tree/master/disaggregate

**Comment by Timelesssssss** [comment]
OK，thanku very much，I will try these!

**Comment by ChristoferNal** [comment]
Hi @Timelesssssss , you can also try:
from nilmtk.legacy.disaggregate import Disaggregator
