### ISSUE TITLE
Question about model used in RNN

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/neural-disaggregator#24]
Hi, I have some question as described as following,
![image](https://user-images.githubusercontent.com/25447481/69539533-ad5dd780-0fbf-11ea-9197-8958a2939198.png)

after 1D Conv, the shape change from (1,1) to (1,16), is that means that **each input value** changed to (1,16)? 
besides, Could you please give me more detail about how the first LSTM work? ex: How many step numbers here etc. 

I am so confused, Thanks!

**Comment by OdysseasKr** [comment]
Hi Hessen. The shape is changed from (1,1) to (1,16) because the convolutional layer has 16 filters (first argument). So, you are right, each input value is changes to (1,16).
Maybe [this](https://predictiveprogrammer.com/wp-content/uploads/2018/06/convolve.gif) visualization helps.

I would not be qualified to explain LSTM to be honest, but [this article](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) was very helpful to me. :)
